apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        - name: my-container2
          image: flask-image:latest
          imagePullPolicy: Never  # Para Minikube local
          ports:
            - containerPort: 8081
          env:
            - name: CLUSTER_NAME
              value: "Minikube Local"
            - name: ENVIRONMENT
              value: "Development"

---
apiVersion: v1
kind: Service
metadata:
  name: my-service2
spec:
  selector:
    app: my-app2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Puerto fijo para acceso local
  type: NodePort
